spring:
  datasource:
    url: jdbc:postgresql://192.168.1.99:26257/burp_wallet?sslmode=disable
  flyway:
    placeholders:
      cdc-sink-url: kafka://192.168.1.99:9092
  kafka:
    bootstrap-servers: 192.168.1.99:9092
