spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/burp_betting?sslmode=disable
  flyway:
    placeholders:
      cdc-sink-url: kafka://localhost:9092
  kafka:
    bootstrap-servers: localhost:9092
burp:
  customer-api-url: http://localhost:8090/api
